import torch

ENV_NAME = "Breakout-v4"  
FRAME_SKIP = 3

FRAME_WIDTH = 84
FRAME_HEIGHT = 84
FRAME_STACK = 4 


CONV1_IN_CHANNELS = FRAME_STACK  
CONV1_OUT_CHANNELS = 32
CONV1_KERNEL_SIZE = 8
CONV1_STRIDE = 4

CONV2_OUT_CHANNELS = 64
CONV2_KERNEL_SIZE = 4
CONV2_STRIDE = 2

CONV3_OUT_CHANNELS = 64
CONV3_KERNEL_SIZE = 3
CONV3_STRIDE = 1

FC1_UNITS_IN = CONV3_OUT_CHANNELS * 7 * 7 
FC1_UNITS_OUT = 512

FC2_UNITS_IN = FC1_UNITS_OUT 

ACTION_SIZE = 4 

BATCH_SIZE = 16
GAMMA = 0.99
EPSILON = 1.0
EPSILON_MIN = 0.05
EPSILON_MAX = 1.0
EPSILON_DECAY = 0.001

LEARNING_RATE = 0.00025
BUFFER_SIZE = 80000
TARGET_UPDATE = 2000
NUM_EPISODES = 1000
NUM_EPISODES_SAVE = 20
PASSOS_POR_EPISODIO = 3000

PASSOS_MULT_RECOMPENSA = 500
MULTIPLICAOR_RECOMPENSA = 2

PENALIDADE_LOST_LIFE = -1

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

MODEL_DIR = 'logs'
MODEL_FILENAME = "dqn_model_1560.pth"
